# Generated by Django 2.1.2 on 2018-10-29 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=100)),
                ('Raza', models.CharField(max_length=100)),
                ('Caracteristicas', models.TextField()),
                ('estado', models.TextField(choices=[('Espera', 'Espera'), ('Adoptado', 'Adoptado')], default='Espera')),
                ('picture', models.ImageField(default='default.jpg', upload_to='user_pics')),
            ],
        ),
    ]
